import { Cargo } from "./cargo.model";
import { Funcao } from "./funcao.model";
import { Grupo } from "./grupo.model";
import { Igreja } from "./igreja.model";
import { Igrejagrupo } from "./igrejagrupo.model";

export class Membro {
  id?: number;
  nome?: string;
  sexo?: string;
  nascimento?: Date;
  estadoCivil?: string;
  naturalidade?: string;
  identidade?: string;
  cpf?: string;
  escolaridade?: string;
  profissao?: string;
  inativo?: boolean;
  tipoSanguineo?: string;
  codigo?: string;
  secretkey?: string;
  email?: string;
  password?: string;
  celular?: string;
  telefone?: string;
  cep?: string;
  uf?: string;
  localidade?: string;
  bairro?: string;
  logradouro?: string;
  numero?: string;
  conjugueNome?: string;
  paiNome?: string;
  maeNome?: string;
  conversaoData?: Date;
  batismoData?: Date;
  batismoIgreja?: string;
  convertido?: boolean;
  batizado?: boolean;
  tipo?: string;
  convencao?: string;
  entradaData?: Date;
  entradaMotivo?: string;
  igrejaOrigem?: string;
  igrejaDestino?: string;
  saidaData?: Date;
  saidaMotivo?: string;
  igrejagrupo?: Igrejagrupo;
  igreja?: Igreja;
  grupos?: Grupo[];
  funcoes?: Funcao[];
  cargo?: Cargo;
  ordenacaoData?: Date;
  acompanhadorNome?: string;
  discipuladorNome?: string;
  //presencas?: Presenca[];
  //inscricoes?: Inscricao[];
  //reunioesResponsavel?: Reuniao[];
  //feeds?: Feed[];
  //documentos?: Documento[];
}
